# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['scripts/task_search.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('chromedriver.exe', '.'),
        ('config', 'config'),
        ('data', 'data'),
        ('scripts/floating_control_panel.py', 'scripts'),
        ('scripts/__init__.py', 'scripts'),
        ('src', 'src'),
    ],
    hiddenimports=[
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.chrome',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.support',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support.expected_conditions',
        'selenium.webdriver.common.by',
        'selenium.webdriver.common.action_chains',
        'selenium.webdriver.common.keys',
        'selenium.common.exceptions',
        'requests',
        'json',
        'time',
        'os',
        'sys',
        'tkinter',
        'tkinter.ttk',
        'threading',
        'pyperclip',
        'webbrowser',
        'subprocess',
        'urllib.parse',
        'datetime',
        'keyboard',
        'PIL',
        'PIL.Image',
        'cv2',
        'numpy',
        'lxml',
        'bs4',
        'beautifulsoup4',
        'scripts.floating_control_panel',
        'src.automation.yuanbao_client',
        'src.api.yuanqi_client',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='TaskSearchTool',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)